#!/bin/bash

# extensions directory
mkdir -p ~/.gemini/extensions

# vision
git clone https://github.com/automateyournetwork/GeminiCLI_Vision_Extension.git ~/.gemini/extensions/vision

# screenshare
git clone https://github.com/automateyournetwork/GeminiCLI_ScreenShare_Extension.git ~/.gemini/extensions/screenshare
